In [203]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import dataframe_image as dfi

from sklearn.preprocessing import MinMaxScaler
import warnings
warnings.filterwarnings('ignore')

In [3]:
url='https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures'
r=requests.get(url)

In [7]:
soup=BeautifulSoup(r.text, 'html.parser')
table=soup.find('table')

In [9]:
rows=table.find_all('tr')

In [13]:
headers=[x.text for x in rows[0].find_all('th')]
headers

['Wk',
 'Day',
 'Date',
 'Time',
 'Home',
 'xG',
 'Score',
 'xG',
 'Away',
 'Attendance',
 'Venue',
 'Referee',
 'Match Report',
 'Notes']

In [151]:
headers=['GW',
 'Day',
 'Date',
 'Time',
 'Home',
 'xG_Home',
 'Score',
 'xG_Away',
 'Away',
 'Attendance',
 'Venue',
 'Referee',
 'Match Report',
 'Notes']

In [186]:
data=[]
for row in rows[1:]:
    if row.find('th').text !='':
        temp=[]
        temp.append(int(row.find('th').text))
        temp.extend([x.text for x in row.find_all('td')])
        data.append(temp)

In [187]:
df=pd.DataFrame(data, columns=headers)

In [188]:
df=df[['GW', 'Date','Home', 'Away', 'xG_Home', 'xG_Away', 'Score']]
df

     GW        Date             Home             Away xG_Home xG_Away Score
0     1  2021-08-13        Brentford          Arsenal     1.3     1.5   2–0
1     1  2021-08-14   Manchester Utd     Leeds United     1.5     0.6   5–1
2     1  2021-08-14   Leicester City           Wolves     0.8     1.1   1–0
3     1  2021-08-14          Burnley         Brighton     1.1     1.2   1–2
4     1  2021-08-14          Watford      Aston Villa     1.2     1.1   3–2
5     1  2021-08-14          Chelsea   Crystal Palace     0.9     0.3   3–0
6     1  2021-08-14          Everton      Southampton     2.4     0.7   3–1
7     1  2021-08-14     Norwich City        Liverpool     1.4     2.0   0–3
8     1  2021-08-15    Newcastle Utd         West Ham     1.4     2.2   2–4
9     1  2021-08-15        Tottenham  Manchester City     1.3     1.9   1–0
10    2  2021-08-21        Liverpool          Burnley     2.9     0.7   2–0
11    2  2021-08-21      Aston Villa    Newcastle Utd     1.1     0.7   2–0
12    2  2021-08-21  Manchester City     Norwich City     2.7     0.1   5–0
13    2  2021-08-21   Crystal Palace        Brentford     0.6     0.9   0–0
14    2  2021-08-21     Leeds United          Everton     1.5     2.1   2–2
15    2  2021-08-21         Brighton          Watford     1.5     0.8   2–0
16    2  2021-08-22      Southampton   Manchester Utd     0.8     1.5   1–1
17    2  2021-08-22           Wolves        Tottenham     1.4     1.5   0–1
18    2  2021-08-22          Arsenal          Chelsea     0.3     2.9   0–2
19    2  2021-08-23         West Ham   Leicester City     2.5     0.8   4–1
20    3  2021-08-28  Manchester City          Arsenal     3.8     0.1   5–0
21    3  2021-08-28     Norwich City   Leicester City     1.6     1.3   1–2
22    3  2021-08-28         West Ham   Crystal Palace     1.2     0.7   2–2
23    3  2021-08-28    Newcastle Utd      Southampton     1.4     3.6   2–2
24    3  2021-08-28      Aston Villa        Brentford     0.6     1.2   1–1
25    3  2021-08-28         Brighton          Everton     1.0     1.6   0–2
26    3  2021-08-28        Liverpool          Chelsea     2.7     0.8   1–1
27    3  2021-08-29        Tottenham          Watford     0.9     0.6   1–0
28    3  2021-08-29          Burnley     Leeds United     1.4     1.5   1–1
29    3  2021-08-29           Wolves   Manchester Utd     1.8     0.6   0–1
..   ..         ...              ...              ...     ...     ...   ...
350  36  2022-05-07          Chelsea           Wolves
351  36  2022-05-07        Liverpool        Tottenham
352  36  2022-05-07        Brentford      Southampton
353  36  2022-05-07     Norwich City         West Ham
354  36  2022-05-07   Crystal Palace          Watford
355  36  2022-05-07          Arsenal     Leeds United
356  36  2022-05-07          Burnley      Aston Villa
357  36  2022-05-07  Manchester City    Newcastle Utd
358  36  2022-05-07         Brighton   Manchester Utd
359  36  2022-05-07   Leicester City          Everton
360  37  2022-05-15   Manchester Utd          Chelsea
361  37  2022-05-15          Everton        Brentford
362  37  2022-05-15     Leeds United         Brighton
363  37  2022-05-15      Aston Villa   Crystal Palace
364  37  2022-05-15          Watford   Leicester City
365  37  2022-05-15      Southampton        Liverpool
366  37  2022-05-15         West Ham  Manchester City
367  37  2022-05-15    Newcastle Utd          Arsenal
368  37  2022-05-15           Wolves     Norwich City
369  37  2022-05-15        Tottenham          Burnley
370  38  2022-05-22     Norwich City        Tottenham
371  38  2022-05-22         Brighton         West Ham
372  38  2022-05-22        Liverpool           Wolves
373  38  2022-05-22        Brentford     Leeds United
374  38  2022-05-22  Manchester City      Aston Villa
375  38  2022-05-22          Burnley    Newcastle Utd
376  38  2022-05-22          Chelsea          Watford
377  38  2022-05-22          Arsenal          Everton
378  38  2022-05-22   Crystal Palace   Manchester Utd
379  38  2022-05-22   Leicester City      Southampton

[380 rows x 7 columns]

In [191]:
def score_splitter(x,h='h'):
    if x=='':
        return 0
    else:
        if h=='h':
            return int(x.split('–')[0])
        else:
            return int(x.split('–')[1])

In [192]:
df["G_Home"]=df.Score.apply(lambda x: score_splitter(x))
df["G_Away"]=df.Score.apply(lambda x: score_splitter(x, h='a'))
df

,GW,Date,Home,Away,xG_Home,xG_Away,Score,G_Home,G_Away
0,1,2021-08-13,Brentford,Arsenal,1.3,1.5,2–0,2,0
1,1,2021-08-14,Manchester Utd,Leeds United,1.5,0.6,5–1,5,1
2,1,2021-08-14,Leicester City,Wolves,0.8,1.1,1–0,1,0
3,1,2021-08-14,Burnley,Brighton,1.1,1.2,1–2,1,2
4,1,2021-08-14,Watford,Aston Villa,1.2,1.1,3–2,3,2
5,1,2021-08-14,Chelsea,Crystal Palace,0.9,0.3,3–0,3,0
6,1,2021-08-14,Everton,Southampton,2.4,0.7,3–1,3,1
7,1,2021-08-14,Norwich City,Liverpool,1.4,2.0,0–3,0,3
8,1,2021-08-15,Newcastle Utd,West Ham,1.4,2.2,2–4,2,4
9,1,2021-08-15,Tottenham,Manchester City,1.3,1.9,1–0,1,0
10,2,2021-08-21,Liverpool,Burnley,2.9,0.7,2–0,2,0
11,2,2021-08-21,Aston Villa,Newcastle Utd,1.1,0.7,2–0,2,0
12,2,2021-08-21,Manchester City,Norwich City,2.7,0.1,5–0,5,0
13,2,2021-08-21,Crystal Palace,Brentford,0.6,0.9,0–0,0,0
14,2,2021-08-21,Leeds United,Everton,1.5,2.1,2–2,2,2
15,2,2021-08-21,Brighton,Watford,1.5,0.8,2–0,2,0
16,2,2021-08-22,Southampton,Manchester Utd,0.8,1.5,1–1,1,1
17,2,2021-08-22,Wolves,Tottenham,1.4,1.5,0–1,0,1
18,2,2021-08-22,Arsenal,Chelsea,0.3,2.9,0–2,0,2
19,2,2021-08-23,West Ham,Leicester City,2.5,0.8,4–1,4,1
20,3,2021-08-28,Manchester City,Arsenal,3.8,0.1,5–0,5,0
21,3,2021-08-28,Norwich City,Leicester City,1.6,1.3,1–2,1,2
22,3,2021-08-28,West Ham,Crystal Palace,1.2,0.7,2–2,2,2
23,3,2021-08-28,Newcastle Utd,Southampton,1.4,3.6,2–2,2,2
24,3,2021-08-28,Aston Villa,Brentford,0.6,1.2,1–1,1,1
25,3,2021-08-28,Brighton,Everton,1.0,1.6,0–2,0,2
26,3,2021-08-28,Liverpool,Chelsea,2.7,0.8,1–1,1,1
27,3,2021-08-29,Tottenham,Watford,0.9,0.6,1–0,1,0
28,3,2021-08-29,Burnley,Leeds United,1.4,1.5,1–1,1,1
29,3,2021-08-29,Wolves,Manchester Utd,1.8,0.6,0–1,0,1
...,...,...,...,...,...,...,...,...,...
350,36,2022-05-07,Chelsea,Wolves,,,,0,0
351,36,2022-05-07,Liverpool,Tottenham,,,,0,0
352,36,2022-05-07,Brentford,Southampton,,,,0,0
353,36,2022-05-07,Norwich City,West Ham,,,,0,0
354,36,2022-05-07,Crystal Palace,Watford,,,,0,0
355,36,2022-05-07,Arsenal,Leeds United,,,,0,0
356,36,2022-05-07,Burnley,Aston Villa,,,,0,0
357,36,2022-05-07,Manchester City,Newcastle Utd,,,,0,0
358,36,2022-05-07,Brighton,Manchester Utd,,,,0,0
359,36,2022-05-07,Leicester City,Everton,,,,0,0
360,37,2022-05-15,Manchester Utd,Chelsea,,,,0,0
361,37,2022-05-15,Everton,Brentford,,,,0,0
362,37,2022-05-15,Leeds United,Brighton,,,,0,0
363,37,2022-05-15,Aston Villa,Crystal Palace,,,,0,0
364,37,2022-05-15,Watford,Leicester City,,,,0,0
365,37,2022-05-15,Southampton,Liverpool,,,,0,0
366,37,2022-05-15,West Ham,Manchester City,,,,0,0
367,37,2022-05-15,Newcastle Utd,Arsenal,,,,0,0
368,37,2022-05-15,Wolves,Norwich City,,,,0,0
369,37,2022-05-15,Tottenham,Burnley,,,,0,0
370,38,2022-05-22,Norwich City,Tottenham,,,,0,0
371,38,2022-05-22,Brighton,West Ham,,,,0,0
372,38,2022-05-22,Liverpool,Wolves,,,,0,0
373,38,2022-05-22,Brentford,Leeds United,,,,0,0
374,38,2022-05-22,Manchester City,Aston Villa,,,,0,0
375,38,2022-05-22,Burnley,Newcastle Utd,,,,0,0
376,38,2022-05-22,Chelsea,Watford,,,,0,0
377,38,2022-05-22,Arsenal,Everton,,,,0,0
378,38,2022-05-22,Crystal Palace,Manchester Utd,,,,0,0
379,38,2022-05-22,Leicester City,Southampton,,,,0,0

In [193]:
team_abb={'Everton':'EVE', 'Aston Villa':'AVL',
          'Leicester City':'LEI', 'Arsenal':'ARS',
          'Liverpool':'LIV','Tottenham':'TOT', 
          'Chelsea':'CHE', 'Leeds United':'LEE', 
          'Newcastle Utd':'NEW','West Ham':'WHU', 
          'Southampton':'SOU', 'Crystal Palace':'CRY', 
          'Wolves':'WOL','Manchester City':'MCI', 
          'Brighton':'BHA', 'Manchester Utd':'MUN', 
          'Watford':'WAT','Burnley':'BUR', 
          'Brentford':'BRE', 'Norwich City':'NOR'}

In [194]:
df.Home=df.Home.apply(lambda x:team_abb[x])
df.Away=df.Away.apply(lambda x:team_abb[x])
df.drop(['Score','Date'], axis=1, inplace=True)
df.head()

   GW Home Away xG_Home xG_Away  G_Home  G_Away
0   1  BRE  ARS     1.3     1.5       2       0
1   1  MUN  LEE     1.5     0.6       5       1
2   1  LEI  WOL     0.8     1.1       1       0
3   1  BUR  BHA     1.1     1.2       1       2
4   1  WAT  AVL     1.2     1.1       3       2

In [196]:
def xG_converter(x):
    try:
        return float(x)
    except:
        return 0
df.xG_Away=df.xG_Away.apply(lambda x:xG_converter(x))
df.xG_Home=df.xG_Home.apply(lambda x:xG_converter(x))

In [197]:
df['GD']=df.G_Home-df.G_Away
df['Pts_Home']=df.GD.apply(lambda x : 3 if x>0 else (0 if x<0 else 1))
df['Pts_Away']=df.GD.apply(lambda x : 0 if x>0 else (3 if x<0 else 1))
df.head()

   GW Home Away  xG_Home  xG_Away  G_Home  G_Away  GD  Pts_Home  Pts_Away
0   1  BRE  ARS      1.3      1.5       2       0   2         3         0
1   1  MUN  LEE      1.5      0.6       5       1   4         3         0
2   1  LEI  WOL      0.8      1.1       1       0   1         3         0
3   1  BUR  BHA      1.1      1.2       1       2  -1         0         3
4   1  WAT  AVL      1.2      1.1       3       2   1         3         0

In [198]:
gw_last=3
gw_next=gw_last+1

In [199]:
df_temp=pd.DataFrame({'Team':list(team_abb.values())})
df_temp['M_h']=df_temp.Team\
.apply(lambda x:df[df.Home==x][df.GW<gw_next].count()[0])

df_temp['M_a']=df_temp.Team\
.apply(lambda x:df[df.Away==x][df.GW<gw_next].count()[0])

df_temp['M']=df_temp.M_h+df_temp.M_a

df_temp['xG_h']=df_temp.Team\
.apply(lambda x:df.xG_Home[df.Home==x][df.GW<gw_next].sum())

df_temp['xG_a']=df_temp.Team\
.apply(lambda x:df.xG_Away[df.Away==x][df.GW<gw_next].sum())

df_temp['xG']=df_temp.xG_a+df_temp.xG_h

df_temp['xGpm_h']=df_temp.xG_h/df_temp.M_h
df_temp['xGpm_a']=df_temp.xG_a/df_temp.M_a
df_temp['xGpm']=df_temp.xG/df_temp.M

df_temp['xGA_h']=df_temp.Team\
.apply(lambda x:df.xG_Away[df.Home==x][df.GW<gw_next].sum())

df_temp['xGA_a']=df_temp.Team\
.apply(lambda x:df.xG_Home[df.Away==x][df.GW<gw_next].sum())

df_temp['xGA']=df_temp.xGA_a+df_temp.xGA_h

df_temp['xGApm_h']=df_temp.xGA_h/df_temp.M_h
df_temp['xGApm_a']=df_temp.xGA_a/df_temp.M_a
df_temp['xGApm']=df_temp.xGA/df_temp.M

df_temp['delta_xGpm']=df_temp.xGpm-df_temp.xGApm


df_temp['P_h']=df_temp.Team\
.apply(lambda x:df.Pts_Home[df.Home==x][df.GW<gw_next].sum())

df_temp['P_a']=df_temp.Team\
.apply(lambda x:df.Pts_Away[df.Away==x][df.GW<gw_next].sum())

df_temp['P']=df_temp.P_a+df_temp.P_h

df_temp['Ppm_h']=df_temp.P_h/df_temp.M_h
df_temp['Ppm_a']=df_temp.P_a/df_temp.M_a
df_temp['Ppm']=df_temp.P/df_temp.M

df_temp['G_h']=df_temp.Team\
.apply(lambda x:df.G_Home[df.Home==x][df.GW<gw_next].sum())

df_temp['G_a']=df_temp.Team\
.apply(lambda x:df.G_Away[df.Away==x][df.GW<gw_next].sum())

df_temp['G']=df_temp.G_a+df_temp.G_h

df_temp['GA_h']=df_temp.Team\
.apply(lambda x:df.G_Away[df.Home==x][df.GW<gw_next].sum())

df_temp['GA_a']=df_temp.Team\
.apply(lambda x:df.G_Home[df.Away==x][df.GW<gw_next].sum())

df_temp['GA']=df_temp.GA_a+df_temp.GA_h

df_temp['GD']=df_temp.G-df_temp.GA

C:\Users\ABCD\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\ABCD\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [206]:
df_temp

,Team,M_h,M_a,M,xG_h,xG_a,xG,xGpm_h,xGpm_a,xGpm,...,Ppm_h,Ppm_a,Ppm,G_h,G_a,G,GA_h,GA_a,GA,GD
0,EVE,1,2,3,2.4,3.7,6.1,2.40,1.85,2.033333,...,3.0,2.0,2.333333,3,4,7,1,2,3,4
1,AVL,2,1,3,1.7,1.1,2.8,0.85,1.10,0.933333,...,2.0,0.0,1.333333,3,2,5,1,3,4,1
2,LEI,1,2,3,0.8,2.1,2.9,0.80,1.05,0.966667,...,3.0,1.5,2.000000,1,3,4,0,5,5,-1
3,ARS,1,2,3,0.3,1.6,1.9,0.30,0.80,0.633333,...,0.0,0.0,0.000000,0,0,0,2,7,9,-9
4,LIV,2,1,3,5.6,2.0,7.6,2.80,2.00,2.533333,...,2.0,3.0,2.333333,3,3,6,1,0,1,5
5,TOT,2,1,3,2.2,1.5,3.7,1.10,1.50,1.233333,...,3.0,3.0,3.000000,2,1,3,0,0,0,3
6,CHE,1,2,3,0.9,3.7,4.6,0.90,1.85,1.533333,...,3.0,2.0,2.333333,3,3,6,0,1,1,5
7,LEE,1,2,3,1.5,2.1,3.6,1.50,1.05,1.200000,...,1.0,0.5,0.666667,2,2,4,2,6,8,-4
8,NEW,2,1,3,2.8,0.7,3.5,1.40,0.70,1.166667,...,0.5,0.0,0.333333,4,0,4,6,2,8,-4
9,WHU,2,1,3,3.7,2.2,5.9,1.85,2.20,1.966667,...,2.0,3.0,2.333333,6,4,10,3,2,5,5
10,SOU,1,2,3,0.8,4.3,5.1,0.80,2.15,1.700000,...,1.0,0.5,0.666667,1,3,4,1,5,6,-2
11,CRY,1,2,3,0.6,1.0,1.6,0.60,0.50,0.533333,...,1.0,0.5,0.666667,0,2,2,0,5,5,-3
12,WOL,2,1,3,3.2,1.1,4.3,1.60,1.10,1.433333,...,0.0,0.0,0.000000,0,0,0,2,1,3,-3
13,MCI,2,1,3,6.5,1.9,8.4,3.25,1.90,2.800000,...,3.0,0.0,2.000000,10,0,10,0,1,1,9
14,BHA,2,1,3,2.5,1.2,3.7,1.25,1.20,1.233333,...,1.5,3.0,2.000000,2,2,4,2,1,3,1
15,MUN,1,2,3,1.5,2.1,3.6,1.50,1.05,1.200000,...,3.0,2.0,2.333333,5,2,7,1,1,2,5
16,WAT,1,2,3,1.2,1.4,2.6,1.20,0.70,0.866667,...,3.0,0.0,1.000000,3,0,3,2,3,5,-2
17,BUR,2,1,3,2.5,0.7,3.2,1.25,0.70,1.066667,...,0.5,0.0,0.333333,2,0,2,3,2,5,-3
18,BRE,1,2,3,1.3,2.1,3.4,1.30,1.05,1.133333,...,3.0,1.0,1.666667,2,1,3,0,1,1,2
19,NOR,2,1,3,3.0,0.1,3.1,1.50,0.10,1.033333,...,0.0,0.0,0.000000,1,0,1,5,5,10,-9

In [200]:
df_temp[['Team','M','P','GD','G','GA' ]].sort_values(by=['P','GD'], ascending=False)\
.style.background_gradient(cmap='RdYlGn',subset=['GA'])

In [202]:
df_fix=df[df.GW>gw_last].iloc[:,:3].reset_index()

def predict_xg(df_fix):
    df_fix['G_home']=0.0
    df_fix['G_away']=0.0

    for i in range(df_fix.shape[0]):
        df_fix.G_home[i]=(df_temp.xGpm[df_temp.Team==df_fix.Home[i]].sum()+
                       df_temp.xGApm[df_temp.Team==df_fix.Away[i]].sum())/2
        df_fix.G_away[i]=(df_temp.xGpm[df_temp.Team==df_fix.Away[i]].sum()+
                       df_temp.xGApm[df_temp.Team==df_fix.Home[i]].sum())/2

    df_fix['GD']=df_fix['G_home']-df_fix['G_away']
    df_fix['GS']=df_fix['G_home']+df_fix['G_away']
    df_fix=df_fix.sort_values(by='GD', ascending=False)
    return df_fix

df_fix=predict_xg(df_fix)

df_styled=df_fix.iloc[:,1:][df_fix.GW==gw_next].style.background_gradient(cmap='RdYlGn',subset=['GD','GS']).hide_index()
dfi.export(df_styled,"mytable.png")
df_styled

C:\Users\ABCD\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\ABCD\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

NameError: name 'dfi' is not defined

In [205]:
gw_dict={}
for i in range(1,5):
    gw_dict.update({str("GW"+str(gw_last+i)):gw_last+i})


df_fdr=pd.DataFrame({'Team':df_temp.Team})

for GW in gw_dict.keys():
    temp_df=df_fix[df_fix.GW==gw_dict[GW]]

    df_fdr[GW]=df_fdr.Team\
    .apply(lambda x:(temp_df[temp_df.Home==x].GD.sum()) 
           if x in (temp_df.Home.unique()) 
           else -temp_df[temp_df.Away==x].GD.sum())
    
sc=MinMaxScaler()
df_fdr['Mean']=df_fdr.mean(axis=1)
for col in gw_dict.keys():
    df_fdr[col]=sc.fit_transform(np.array(df_fdr[col]).reshape(-1,1))
df_fdr=df_fdr.sort_values(by='Mean', ascending=False)
df_fdr.style.background_gradient(cmap='RdYlGn',
                                 subset=list(gw_dict.keys()))

In [127]:
temp=temp[['Home', 'Away', 'xG_h', 'xG_a', 'G_h', 'G_a']]

In [133]:
temp['GD']=temp.G_h-temp.G_a
def res_calculator(x):
    if x>0:
        return 'W'
    elif x==0:
        return 'D'
    else:
        return 'L'
temp['res']=temp.GD.apply(lambda x:res_calculator(x))
temp

C:\Users\ABCD\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\ABCD\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

   Home Away  xG_h  xG_a  G_h  G_a  GD res
0   BRE  ARS   1.3   1.5    2    0   2   W
1   MUN  LEE   1.5   0.6    5    1   4   W
2   LEI  WOL   0.8   1.1    1    0   1   W
3   BUR  BHA   1.1   1.2    1    2  -1   L
4   WAT  AVL   1.2   1.1    3    2   1   W
5   CHE  CRY   0.9   0.3    3    0   3   W
6   EVE  SOU   2.4   0.7    3    1   2   W
7   NOR  LIV   1.4   2.0    0    3  -3   L
8   NEW  WHU   1.4   2.2    2    4  -2   L
9   TOT  MCI   1.3   1.9    1    0   1   W
10  LIV  BUR   2.9   0.7    2    0   2   W
11  AVL  NEW   1.1   0.7    2    0   2   W
12  MCI  NOR   2.7   0.1    5    0   5   W
13  CRY  BRE   0.6   0.9    0    0   0   D
14  LEE  EVE   1.5   2.1    2    2   0   D
15  BHA  WAT   1.5   0.8    2    0   2   W
16  SOU  MUN   0.8   1.5    1    1   0   D
17  WOL  TOT   1.4   1.5    0    1  -1   L
18  ARS  CHE   0.3   2.9    0    2  -2   L
19  WHU  LEI   2.5   0.8    4    1   3   W
20  MCI  ARS   3.8   0.1    5    0   5   W
21  NOR  LEI   1.6   1.3    1    2  -1   L
22  WHU  CRY   1.2   0.7    2    2   0   D
23  NEW  SOU   1.4   3.6    2    2   0   D
24  AVL  BRE   0.6   1.2    1    1   0   D
25  BHA  EVE   1.0   1.6    0    2  -2   L
26  LIV  CHE   2.7   0.8    1    1   0   D
27  TOT  WAT   0.9   0.6    1    0   1   W
28  BUR  LEE   1.4   1.5    1    1   0   D
29  WOL  MUN   1.8   0.6    0    1  -1   L

In [136]:
temp.columns

Index(['Home', 'Away', 'xG_h', 'xG_a', 'G_h', 'G_a', 'GD', 'res'], dtype='object')

In [137]:
temp.pivot_table(index='Home', values=['xG_h','xG_a', 'G_h', 'G_a'])

      G_a  G_h  xG_a  xG_h
Home
ARS   2.0  0.0  2.90  0.30
AVL   0.5  1.5  0.95  0.85
BHA   1.0  1.0  1.20  1.25
BRE   0.0  2.0  1.50  1.30
BUR   1.5  1.0  1.35  1.25
CHE   0.0  3.0  0.30  0.90
CRY   0.0  0.0  0.90  0.60
EVE   1.0  3.0  0.70  2.40
LEE   2.0  2.0  2.10  1.50
LEI   0.0  1.0  1.10  0.80
LIV   0.5  1.5  0.75  2.80
MCI   0.0  5.0  0.10  3.25
MUN   1.0  5.0  0.60  1.50
NEW   3.0  2.0  2.90  1.40
NOR   2.5  0.5  1.65  1.50
SOU   1.0  1.0  1.50  0.80
TOT   0.0  1.0  1.25  1.10
WAT   2.0  3.0  1.10  1.20
WHU   1.5  3.0  0.75  1.85
WOL   1.0  0.0  1.05  1.60

In [ ]:
df['GD']=df.G_Home-df.G_Away
df['Pts_Home']=df.GD.apply(lambda x : 3 if x>0 else (0 if x<0 else 1))
df['Pts_Away']=df.GD.apply(lambda x : 0 if x>0 else (3 if x<0 else 1))
df.head()

In [135]:
livetbl=temp.pivot_table(index='Home', values='xG_h', aggfunc='count').reset_index()
livetbl=livetbl.rename(columns={'Home':'Team', 'xG_h':'M_h'})
livetbl

   Team  M_h
0   ARS    1
1   AVL    2
2   BHA    2
3   BRE    1
4   BUR    2
5   CHE    1
6   CRY    1
7   EVE    1
8   LEE    1
9   LEI    1
10  LIV    2
11  MCI    2
12  MUN    1
13  NEW    2
14  NOR    2
15  SOU    1
16  TOT    2
17  WAT    1
18  WHU    2
19  WOL    2